### PR TITLE
Exception when $Object.Year is not valid when adding to a UserCustomList

### PR DESCRIPTION
**Pull request by henrikfroehling**

### CODE REVIEW

**Review by TheUltimateC0der — APPROVED** [review]

**Comment by TheUltimateC0der** [comment]
When can i expect this to be available via nuget.org ?

**Comment by henrikfroehling** [comment]
@TheUltimateC0der 
> When can i expect this to be available via nuget.org ?

In the next version => 1.0.2

**Comment by TheUltimateC0der** [comment]
And when will this version be available via nuget.org ?

**Comment by henrikfroehling** [comment]
> And when will this version be available via nuget.org ?

Sometime during the next hour.

**Comment by henrikfroehling** [comment]
@TheUltimateC0der 
Release 1.0.2 is now available on NuGet.org => https://www.nuget.org/packages/Trakt.NET/1.0.2

**Pull request merged**
